/**
 * Order Brief Type Definitions
 * Phase 1: Evidence-based extraction, human consent placeholder
 */

import type {
  OrderBrief,
  OrderBriefRevision,
  OrderBriefStatus,
  OrderBriefRevisionStatus,
  OrderBriefFieldState,
} from "@prisma/client";

export type {
  OrderBrief,
  OrderBriefRevision,
  OrderBriefStatus,
  OrderBriefRevisionStatus,
  OrderBriefFieldState,
};

// =============================================================================
// FIELD STATE & EVIDENCE
// =============================================================================

/**
 * Every field has explicit state and evidence tracking
 */
export interface FieldWithEvidence<T = unknown> {
  value: T | null;
  rawText: string | null; // Original text from chat
  state: OrderBriefFieldState;
  evidenceMessageIds: string[];
  evidenceQuotes: string[]; // Brief excerpts for display
  sourceType: "CHAT" | "CATALOG" | "CREATOR_DATA" | "HUMAN_EDIT";
  lastEditedBy: "BUYER" | "CREATOR" | null;
  notes: string | null;
}

/**
 * Budget constraint type
 */
export type BudgetConstraint = "TARGET" | "MAXIMUM" | "RANGE";

/**
 * Fulfillment method
 */
export type FulfillmentMethod = "DELIVERY" | "PICKUP" | "UNDECIDED";

/**
 * Visual reference intent for Phase 2
 */
export type VisualReferenceIntent =
  | "STYLE_DIRECTION"
  | "EXACT_VARIANT"
  | "SIZE_REFERENCE"
  | "COLOR_REFERENCE";

// =============================================================================
// ORDER BRIEF SNAPSHOT SCHEMA
// =============================================================================

/**
 * Complete Order Brief snapshot structure
 * This is stored as JSON in OrderBriefRevision.snapshotJson
 */
export interface OrderBriefSnapshot {
  schemaVersion: string;
  
  // Product information
  product: {
    productType: FieldWithEvidence<string>;
    categoryId: FieldWithEvidence<string>;
    productId: FieldWithEvidence<string>;
    variantId: FieldWithEvidence<string>;
    quantity: FieldWithEvidence<number>;
  };

  // Occasion and recipient
  occasion: {
    occasion: FieldWithEvidence<string>;
    recipientDescription: FieldWithEvidence<string>;
  };

  // Visual preferences
  visual: {
    originalVisualTerms: FieldWithEvidence<string>;
    colorPreference: FieldWithEvidence<string>;
    stylePreference: FieldWithEvidence<string>;
    selectedVisualReferences: FieldWithEvidence<string[]>; // Phase 2
  };

  // Size and specifications
  size: {
    requestedSize: FieldWithEvidence<string>;
    dimensions: FieldWithEvidence<string>;
    sizeReference: FieldWithEvidence<string>;
  };

  // Financial
  financial: {
    buyerBudget: FieldWithEvidence<number>;
    budgetCurrency: FieldWithEvidence<string>;
    budgetConstraint: FieldWithEvidence<BudgetConstraint>;
    creatorQuotedPrice: FieldWithEvidence<number>; // Only from creator/catalog
    quotedPriceSource: FieldWithEvidence<string>;
  };

  // Personalization
  personalization: {
    personalizationType: FieldWithEvidence<string>;
    cardText: FieldWithEvidence<string>;
    customName: FieldWithEvidence<string>;
    otherCustomization: FieldWithEvidence<string>;
  };

  // Fulfillment
  fulfillment: {
    requestedFulfillmentDate: FieldWithEvidence<string>; // ISO date string
    requestedFulfillmentTime: FieldWithEvidence<string>;
    requestedTimeZone: FieldWithEvidence<string>;
    creatorCommittedDate: FieldWithEvidence<string>; // Only from creator
    creatorCommittedTime: FieldWithEvidence<string>; // Only from creator
    fulfillmentMethod: FieldWithEvidence<FulfillmentMethod>;
    deliveryArea: FieldWithEvidence<string>; // General area, not full address
  };

  // Additional notes
  notes: {
    specialNotes: FieldWithEvidence<string>;
    exclusions: FieldWithEvidence<string>;
    unresolvedItems: FieldWithEvidence<string[]>;
  };

  // Policy references (Phase 3)
  policies: {
    revisionPolicyVersionId: FieldWithEvidence<string>;
    cancellationPolicyVersionId: FieldWithEvidence<string>;
    disputePolicyVersionId: FieldWithEvidence<string>;
  };
}

// =============================================================================
// AI EXTRACTION OUTPUT
// =============================================================================

/**
 * Assumption made by AI that needs confirmation
 */
export interface BriefAssumption {
  fieldKey: string;
  candidateValue: unknown;
  reason: string;
  evidenceMessageIds: string[];
}

/**
 * Conflict detected in conversation
 */
export interface BriefConflict {
  fieldKey: string;
  conflictingValues: Array<{
    value: unknown;
    messageId: string;
    quote: string;
  }>;
  reason: string;
}

/**
 * Clarification question generated by AI
 */
export interface ClarificationQuestion {
  fieldKey: string;
  question: string;
  priority: number; // 1 = highest
  reason: string;
}

/**
 * AI extraction result from OpenRouter
 */
export interface ExtractionResult {
  schemaVersion: string;
  fields: Partial<OrderBriefSnapshot>;
  assumptions: BriefAssumption[];
  conflicts: BriefConflict[];
  missingCriticalFields: string[];
  clarificationQuestions: ClarificationQuestion[];
  humanSummary: string;
}

// =============================================================================
// MESSAGE EVIDENCE
// =============================================================================

/**
 * Message used as evidence in brief
 */
export interface MessageEvidence {
  id: string;
  content: string;
  role: "BUYER" | "CREATOR";
  createdAt: Date;
  quote?: string; // Relevant excerpt
}

// =============================================================================
// COMPLETENESS & READINESS
// =============================================================================

/**
 * Brief completeness indicator
 */
export interface BriefCompleteness {
  totalRequiredFields: number;
  filledFields: number;
  percentage: number;
  missingFields: string[];
}

/**
 * Agreement readiness (Phase 3)
 */
export interface AgreementReadiness {
  isReady: boolean;
  confirmedFields: number;
  totalCriticalFields: number;
  hasConflicts: boolean;
  hasCreatorQuote: boolean;
  hasCommittedDate: boolean;
  blockers: string[];
}

// =============================================================================
// API REQUEST/RESPONSE TYPES
// =============================================================================

/**
 * Request to compile brief from conversation
 */
export interface CompileBriefRequest {
  conversationId: string;
  orderBriefId?: string; // If updating existing brief
  expectedRevision?: number; // For optimistic concurrency
}

/**
 * Request to update draft field
 */
export interface UpdateDraftFieldRequest {
  briefId: string;
  expectedRevision: number;
  fieldPath: string; // e.g., "product.quantity"
  value: unknown;
  editReason?: string;
}

/**
 * Response from compile endpoint
 */
export interface CompileBriefResponse {
  briefId: string;
  revisionId: string;
  version: number;
  snapshot: OrderBriefSnapshot;
  assumptions: BriefAssumption[];
  conflicts: BriefConflict[];
  clarifications: ClarificationQuestion[];
  completeness: BriefCompleteness;
  createdAt: string;
}

/**
 * Response from get brief endpoint
 */
export interface GetBriefResponse {
  brief: OrderBrief & {
    currentRevision: OrderBriefRevision | null;
  };
  snapshot: OrderBriefSnapshot | null;
  clarifications: ClarificationQuestion[];
  completeness: BriefCompleteness;
  permissions: {
    canEdit: boolean;
    canCompile: boolean;
    canAgree: boolean; // Phase 3
    userParty: "BUYER" | "CREATOR" | null;
  };
}

// =============================================================================
// CONVERSATION CONTEXT
// =============================================================================

/**
 * Conversation message for AI processing
 */
export interface ConversationMessage {
  id: string;
  role: "BUYER" | "CREATOR";
  content: string;
  createdAt: Date;
}

/**
 * Conversation participant information
 */
export interface ConversationParticipant {
  userId: string;
  role: "BUYER" | "CREATOR";
  name: string;
  email?: string;
}

/**
 * Full conversation context for extraction
 */
export interface ConversationContext {
  conversationId: string;
  messages: ConversationMessage[];
  participants: ConversationParticipant[];
  productContext?: {
    availableProducts: Array<{
      id: string;
      title: string;
      category: string;
      price: number;
    }>;
    creatorLeadTime?: number;
  };
}
